if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=( git zsh-syntax-highlighting zsh-autosuggestions )

source $ZSH/oh-my-zsh.sh

export EDITOR=nvim
export GIT_EDITOR=nvim
export NVIM_LISTEN_ADDRESS=/tmp/nvimsocket

alias vi="nvim"

alias dc="docker compose"
alias cup="docker compose up -d"
alias cst="docker compose stop"
alias gs="git status"
alias gc="git checkout"
alias gf="git fetch"
alias gp="git pull"
alias gh="git log --pretty=format:'%h %ad | %s%d [%an]' --graph --date=short"

alias cicde="cd ~/Projects/cicde/cicde/"
alias esup="cd ~/Projects/esuperficia/esuperficia/"
alias gbg="cd ~/Projects/gbg/gbg.rts.one/"
alias cnpf="cd ~/Projects/cnpf/rsvm/"
alias lnm="cd ~/Projects/lnm/lnm/"
alias edata="cd ~/Projects/edata/edata-2021"
alias gsp="cd ~/Projects/GSP/gsp"
alias cons="cd ~/Projects/consultari/consultari-publice"

alias sshw="$HOME/go/bin/sshw"

alias sail='sh $([ -f sail ] && echo sail || echo vendor/bin/sail)'
alias sa="sail artisan"
alias sq="sail artisan queue:work"
alias ss="sail shell"
alias st="sail tinker"
alias sup="sail up -d"
alias sst="sail stop"

alias snp='function sailnpmpkg() {
  local path=$1
  shift
  sail shell -c "cd packages/$path && npm run $*"
}'
alias sail-pint='sail exec phprun ./vendor/bin/pint'
alias sail-psalm='sail exec phprun php -d xdebug.mode=off ./vendor/bin/psalm --set-baseline=psalm-baseline.xml'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH=$PATH:$HOME/home/mihail-malai/.local/share/nvim/mason/bin
export PATH="$HOME/bin:$PATH"
export PATH=$HOME/.local/bin:$PATH

unset NVIM_LISTEN_ADDRESS
